version: '3.9'

services:
  db:
    container_name: postgres-springboot
    image: postgres:latest
    environment:
      POSTGRES_USER: aayush
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - pricetracker-network
    restart: unless-stopped


networks:
  pricetracker-network:
    driver: bridge

volumes:
  db:
  redis_data:
