spring.application.name=PriceTracker

spring.datasource.url=jdbc:postgresql://localhost:5332/project
spring.datasource.username=aayush
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6479
spring.cache.type=redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bblakurphy@gmail.com
spring.mail.password=pphplactliykjrls 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.sender.email=bblakurphy@gmail.com
brightdata.wsEndpoint=
scraper.headless=false
jwt.secret=f8J#R9!u3bZ7@4kqP6&1mH8gT0$wLf^D




# Scraper Configuration
scraper.timeout=30000
scraper.max-results=10


# Logging
logging.level.com.project.PriceTracker.scraper=INFO
logging.level.com.microsoft.playwright=WARN